apiVersion: batch/v1
kind: Job
metadata:
  name: loading-job
spec:
  template:
    spec:
      containers:
      - name: loading-job
        image: yash5090/loading:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
