apiVersion: apps/v1
kind: Deployment
metadata:
  name: loading-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: loading
  template:
    metadata:
      labels:
        app: loading
    spec:
      containers:
        - name: loading
          image: yash5090/loading:latest # Replace with the actual image tag
          ports:
            - containerPort: 5000 # Replace with the port your Tetris game listens on
